# Changes here will be overwritten by Copier
_commit: 1.4.0
_src_path: gh:AdrienCos/seedlings
author_email: pierrickcurt@gmail.com
author_name: Pierrick Curt
author_username: pcurt
enable_release_ci: true
package_name: mapio_webserver_back
project_name: mapio_webserver_back
repository_url: https://github.com/pcurt/mapio_webserver_back
short_description: MAPIO webserver front source code
